In [1]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [2]:
import tensorflow as tf
tf.__version__

'2.2.0'

In [3]:
tf.constant(6)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [4]:
tf.constant(6.)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [5]:
tf.constant([True,False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [6]:
tf.constant('I love tf2!!!')

<tf.Tensor: shape=(), dtype=string, numpy=b'I love tf2!!!'>

 **變數類型**

In [7]:
import numpy as np

In [8]:
#Create tf.constant
a = tf.constant([1,2,3])
#Convert np arry to tf
a = np.array([1,2,3])
b = tf.convert_to_tensor(a)

In [9]:
b

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [10]:
#Create tf.Variable
a = tf.ones(6)
b = tf.Variable(a,name='Data_point')
b

<tf.Variable 'Data_point:0' shape=(6,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

In [11]:
b.trainable #check weather trainable

True

In [12]:
#Create 0 matrix
a = tf.zeros([6,6])
#or
b = tf.zeros_like(a)
#or fill -> shape and fill nums
c = tf.fill([6,6],0)

In [13]:
c

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

In [14]:
#Example random by normal distribution
a = tf.random.normal([6,6],mean=0,stddev=1)
#random by truncated normal distribution
b = tf.random.truncated_normal([6,6],mean=0,stddev=1)
#random by uniform
c = tf.random.uniform([6,6],minval=0,maxval=1)

In [15]:
a

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[ 0.24097888,  0.20553762,  0.8995366 ,  1.1600448 ,  0.25291708,
         0.37648833],
       [-0.42466396,  0.6204753 ,  0.18946598,  0.73095596, -0.52937424,
        -0.57800055],
       [-0.3604185 , -0.35277134,  1.3113467 , -0.88858694, -1.2658571 ,
        -2.048099  ],
       [-1.5397677 ,  2.6110299 , -0.78358126, -0.8021525 , -0.80980825,
         0.27005717],
       [ 0.6558137 ,  0.19863158,  0.19837783, -0.14081572, -0.04454594,
         1.2814765 ],
       [-0.8373519 , -0.5468744 ,  0.77884823, -0.16533092, -0.23612665,
        -0.9739968 ]], dtype=float32)>

In [16]:
#Example for select instance
a = tf.ones([1,5,5,3])
a[0][0].shape
#Output shape:TensorShape([5, 3])
a[...,2].shape
#Output shape:TensorShape([1, 5, 5])

TensorShape([1, 5, 5])

In [17]:
#use index select
tf.gather_nd(a,[0]).shape
#Output shape: TensorShape([5, 5, 3])

#select axis=1 , row 2 and 3
tf.gather(a,axis=1,indices=[2,3]).shape
#Output shape: TensorShape([1, 2, 5, 3])

TensorShape([1, 2, 5, 3])

In [18]:
#Sorting

In [19]:
#Example for sort
data = tf.random.normal([10],mean=0,stddev=1)
tf.sort(data,direction='DESCENDING')
#or
tf.gather(data,tf.argsort(data,direction='ASCENDING'))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.7024577 , -0.37213287, -0.17563649, -0.05438402, -0.04834618,
        0.2376566 ,  0.38604498,  0.40747476,  0.6794364 ,  0.8253954 ],
      dtype=float32)>

In [20]:
#Example top_k
top_data = tf.math.top_k(data,k=5)
#Get indies or values
top_data.indices
#or
top_data.values

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.8253954 , 0.6794364 , 0.40747476, 0.38604498, 0.2376566 ],
      dtype=float32)>

In [21]:
data = tf.random.normal([3,3],mean=0,stddev=1)
tf.pad(data,[[1,1],[1,1]])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -1.7263494 ,  0.8009505 ,  1.4661866 ,  0.        ],
       [ 0.        ,  0.441546  , -1.4415514 , -0.03254908,  0.        ],
       [ 0.        , -1.0412214 ,  0.7639621 ,  0.9443403 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
      dtype=float32)>

In [22]:
#Example clipping
tf.clip_by_value(data,0,1)
#range if number less or above fix at 0 or 1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.       , 0.8009505, 1.       ],
       [0.441546 , 0.       , 0.       ],
       [0.       , 0.7639621, 0.9443403]], dtype=float32)>

In [23]:
tf.clip_by_value(data,0,1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.       , 0.8009505, 1.       ],
       [0.441546 , 0.       , 0.       ],
       [0.       , 0.7639621, 0.9443403]], dtype=float32)>

In [24]:
a = tf.fill([2,2],5)
b = tf.fill([2,2],6)
a+b,a*b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 11],
        [11, 11]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[30, 30],
        [30, 30]], dtype=int32)>)

In [25]:
a = tf.fill([2,32,4],5)
b = tf.fill([2,4,6],6)
(a@b).shape # or tf.matmul(a,b)
#Output:TensorShape([2, 32, 6])

TensorShape([2, 32, 6])

In [26]:
#Example for dimension wise
data = [[1,2,3],
      [1,2,3]]

tf_data = tf.cast(data,tf.float32)

mean_all = tf.reduce_mean(tf_data, keepdims=False)
mean_0 = tf.reduce_mean(tf_data, axis=0, keepdims=False)
mean_1 = tf.reduce_mean(tf_data, axis=1, keepdims=False)

In [27]:
mean_all,mean_0,mean_1

(<tf.Tensor: shape=(), dtype=float32, numpy=2.0>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>)

In [28]:
x = tf.random.normal([4,40,12])
(x + tf.random.normal([40,1])).shape
#Output:TensorShape([4, 40, 12])

TensorShape([4, 40, 12])

In [29]:
data_all = tf.split(a,axis=1,num_or_size_splits=2)
data_all[0].shape
#Output:TensorShape([2, 16, 3])
len(data_all)
#Output:2

2

In [30]:
a = tf.constant([1,2,3])
tf.math.argmax(a)

<tf.Tensor: shape=(), dtype=int64, numpy=2>